version: "3.7"

services:
  server1:
    build:
      context: cs2-server-image
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
      - "27020:27020/udp"
    env_file:
      - .env
    volumes:
      - "./steam-login-data:/root/Steam"
      - "./cs2-data:/root/cs2-dedicated"

  server2:
    build:
      context: cs2-server-image
    ports:
      - "27025:27015/udp"
      - "27025:27015/tcp"
      - "27030:27020/udp"
    env_file:
      - .env
    volumes:
      - "./steam-login-data:/root/Steam"
      - "./cs2-data:/root/cs2-dedicated"

  rconpanel:
    image: soren90/rcon-panel
    ports:
      - "3000:3000"
    restart: unless-stopped
